# Generated by Django 2.1.5 on 2023-03-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tudo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created']},
        ),
    ]
